Fix usage of satellite in organization mode
When satellite is used in organization mode, deployments were failing
due to a change on code return on subscription manager. This last will
generate an error any way so this is a bypass.

Tested on queen.

Closes-Bug: #1822725

Change-Id: I0dd65cc752a6bd94bec59f695e55aa85ef8f0192
Signed-off-by: Cyril Lopez <cylopez@redhat.com>
(cherry picked from commit d80a956d7266b12c593060fa0a01ed997771a8ee)

diff --git a/extraconfig/pre_deploy/rhel-registration/scripts/rhel-registration b/extraconfig/pre_deploy/rhel-registration/scripts/rhel-registration
--- a/extraconfig/pre_deploy/rhel-registration/scripts/rhel-registration
+++ b/extraconfig/pre_deploy/rhel-registration/scripts/rhel-registration
@@ -272,8 +272,17 @@ case "${REG_METHOD:-}" in
             fi
 
             rpm -Uvh katello-ca-consumer-latest.noarch.rpm || true
-            retry subscription-manager register $opts
-            retry subscription-manager $repos
+            if [ "$REG_SAT_ORGMODE" = "True" ]; then
+                subscription-manager register $opts || true
+                subscription-manager $repos || true
+                if [ $(subscription-manager status |grep -c "Content Access Mode is set to Organization/Environment") = 0 ]; then
+                    echo "Fail to register the node to satellite in Organization mode"
+                    exit 1
+                fi
+            else
+                retry subscription-manager register $opts
+                retry subscription-manager $repos
+            fi
             yum install -y katello-agent || true # needed for errata reporting to satellite6
             katello-package-upload
 
