Handle difference between future and current container_cli
During upgrade we may have container_cli be Podman but the containers
may still be running on Docker. Handle this situation in the upgrade
tasks which are the last-resort online data migration if user forgot
to trigger them earlier, as they seem to be hitting this issue.

We must support both options at the same time, because the upgrade
code must be idempotent (re-runnable). When running upgrade 1st time,
the containers will be running in Docker, when re-running the upgrade
(e.g. because a part of it failed), the containers will be running in
Podman.

Once we converge onto a single solution and do not have to support
migration, this commit can be reverted.

Change-Id: I933ce754f081ee87ec53d5f8d9c901ab71dceb1e
Closes-Bug: #1802085

diff --git a/docker/services/cinder-api.yaml b/docker/services/cinder-api.yaml
--- a/docker/services/cinder-api.yaml
+++ b/docker/services/cinder-api.yaml
@@ -261,7 +261,17 @@ outputs:
               when: cinder_api_enabled|bool
               tags: validation
             - name: Ensure all online data migrations for Cinder have been applied
-              command: "{{ container_cli }} exec cinder_api cinder-manage db online_data_migrations"
+              shell: |
+                if {{ container_cli }} ps | grep cinder_api; then
+                  {{ container_cli }} exec cinder_api cinder-manage db online_data_migrations
+                # handle situation when container_cli is podman but
+                # the containers are still under docker
+                elif docker ps | grep cinder_api; then
+                  docker exec cinder_api cinder-manage db online_data_migrations
+                else
+                  echo "Error: cinder_api container not found"
+                  exit 1
+                fi
               tags: pre-upgrade
               when:
                 - is_bootstrap_node|bool
diff --git a/docker/services/ironic-api.yaml b/docker/services/ironic-api.yaml
--- a/docker/services/ironic-api.yaml
+++ b/docker/services/ironic-api.yaml
@@ -197,7 +197,17 @@ outputs:
                 - ironic_httpd_enabled|bool
                 - httpd_running|bool
             - name: Ensure all online data migrations for Ironic have been applied
-              command: "{{ container_cli }} exec ironic_api ironic-dbsync --config-file /etc/ironic/ironic.conf online_data_migrations"
+              shell: |
+                if {{ container_cli }} ps | grep ironic_api; then
+                  {{ container_cli }} exec ironic_api ironic-dbsync --config-file /etc/ironic/ironic.conf online_data_migrations
+                # handle situation when container_cli is podman but
+                # the containers are still under docker
+                elif docker ps | grep ironic_api; then
+                  docker exec ironic_api ironic-dbsync --config-file /etc/ironic/ironic.conf online_data_migrations
+                else
+                  echo "Error: ironic_api container not found"
+                  exit 1
+                fi
               tags: pre-upgrade
               when:
                 - is_bootstrap_node|bool
diff --git a/puppet/services/haproxy-public-tls-inject.yaml b/puppet/services/haproxy-public-tls-inject.yaml
--- a/puppet/services/haproxy-public-tls-inject.yaml
+++ b/puppet/services/haproxy-public-tls-inject.yaml
@@ -186,11 +186,31 @@ outputs:
                   register: kolla_cert_exists
 
                 - name: set certificate group on host via container
-                  command: "{{ container_cli }} exec {{container_id.stdout}} chgrp haproxy {{kolla_dir}}{{cert_path}}"
+                  shell: |
+                    if {{ container_cli }} ps | grep {{container_id.stdout}}; then
+                      {{ container_cli }} exec {{container_id.stdout}} chgrp haproxy {{kolla_dir}}{{cert_path}}
+                    # handle situation when container_cli is podman but
+                    # the containers are still under docker
+                    elif docker ps | grep {{container_id.stdout}}; then
+                      docker exec {{container_id.stdout}} chgrp haproxy {{kolla_dir}}{{cert_path}}
+                    else
+                      echo "Error: {{container_id.stdout}} container not found"
+                      exit 1
+                    fi
                   when: kolla_cert_exists.stat.exists
 
                 - name: copy certificate from kolla directory to final location
-                  command: "{{ container_cli }} exec {{container_id.stdout}} cp {{kolla_dir}}{{cert_path}} {{cert_path}}"
+                  shell: |
+                    if {{ container_cli }} ps | grep {{container_id.stdout}}; then
+                      {{ container_cli }} exec {{container_id.stdout}} cp {{kolla_dir}}{{cert_path}} {{cert_path}}
+                    # handle situation when container_cli is podman but
+                    # the containers are still under docker
+                    elif docker ps | grep {{container_id.stdout}}; then
+                      docker exec {{container_id.stdout}} cp {{kolla_dir}}{{cert_path}} {{cert_path}}
+                    else
+                      echo "Error: {{container_id.stdout}} container not found"
+                      exit 1
+                    fi
                   when: kolla_cert_exists.stat.exists
 
                 - name: send restart order to haproxy container
